Kulimo/Kulimo/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView

from django.contrib.auth import views as auth_views

from accueil import urls as accueil_urls
from accueil import views


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include(accueil_urls)),
    
    path('', RedirectView.as_view(url='/accueil')), 

    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True, template_name='login.html'), name='login'),
    path('register/', views.register_request, name='register'),
    path('logout/', auth_views.LogoutView.as_view(next_page='accueil'), name='logout'),

    path('a_propos_de_nous/', views.aboutUs, name = 'aboutUs' ),
    path('nous_joindre/', views.nousJoindre, name = 'nousJoindre' ),
    path('conditions-d-utilisation/', views.conditionsUtilisations, name = 'conditionsUtilisations'),
    path('a_lire/', views.aLire, name = 'a_lire'),

    path("profile_list/", views.profile_list, name="profile_list"),
    path("profile/<int:pk>", views.profile, name="profile"),
    path('dashboard/', views.dashboard, name= 'dashboard'),
    path('rechercher/', views.rechercher, name= 'rechercher'),

    path('accueil/', TemplateView.as_view(template_name='main.html'), name='accueil'), 

    path('profile/checkview', views.checkview, name='checkview'),
    path('send', views.send, name='send'),
    path('rooms/<str:room>/', views.room, name='room'),
    path('getMessages/rooms/<str:room>/', views.getMessages, name='getMessages'),
]

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Kulimo/accueil/urls.py
from django.urls import path
from . import views
from .views import profile_list, profile
from django.conf import settings
from django.conf.urls.static import static

# Fichier qui permet d'associer nos adresses URL à nos méthodes 'views'

app_name = "accueil"

urlpatterns = [
    path("register", views.register_request, name="register"),
    path('a_propos_de_nous', views.aboutUs, name = 'aboutUs' ),
    path('nous_joindre', views.nousJoindre, name = 'nousJoindre' ),
    path('conditions-d-utilisation', views.conditionsUtilisations, name = 'conditionsUtilisations'),
    path('a_lire', views.aLire, name = 'a_lire'),
    path("profile_list/", views.profile_list, name="profile_list"),
    path("profile/<int:pk>", views.profile, name="profile"),
    path('dashboard', views.dashboard, name= 'dashboard'),
    path('rechercher', views.rechercher, name= 'rechercher'),
    path('rooms/<str:room>/', views.room, name='room'),
    path('checkview', views.checkview, name='checkview'),
]

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Kulimo/accueil/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.sessions.models import Session
from django.contrib.auth.signals import user_logged_in

# Fichier qui définit les différents modèles utilisé dans notre application

# Classe importée de Django qui définit les utilisateurs
User= settings.AUTH_USER_MODEL

# Classe qui définit les publications des utiliateurs
class UserPost(models.Model):
    user= models.ForeignKey(User, related_name="userposts", on_delete=models.DO_NOTHING)
    title= models.CharField(max_length=100)
    content= models.TextField()
    date_published= models.DateTimeField(auto_now_add=True)
    image= models.ImageField(upload_to='images')
    url= models.SlugField(max_length=500, unique=True, blank=True, editable=False)
    def save(self, *args, **kwargs):
        self.url= slugify(self.title)
        super(UserPost, self).save(*args, **kwargs)    

# Classe qui définit la page profile des utilisateurs
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

# Classe qui définit une salle de messagerie entre deux utilisateurs
class Room(models.Model):
   name = models.CharField(max_length=1000)

# Classe qui défini un message envoyé par un utilisateur
class Message(models.Model):
   value = models.CharField(max_length=1000)
   date = models.DateTimeField(auto_now_add=True)
   user = models.CharField(max_length=1000)
   room = models.CharField(max_length=1000000)

# Méthode qui crée automatiquement un profil associé à un utilisateur lorsque ce dernier est crée
@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        user_profile = Profile(user=instance)
        user_profile.save()





Kulimo/accueil/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserPost


# Classe qui définit les différents formulaires que l'utilisateur peut remplir


# Le formulaire pour la création d'un compte
class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)


	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user
	
# Le formulaire pour la création d'une publication
class UserPostForm(forms.ModelForm):
	
    class Meta:
        model= UserPost
        fields= ["title", "content", "image"]
        exclude = ("user", )

Kulimo/accueil/views.py
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.template import loader, RequestContext
from .models import UserPost, Profile, Room, Message
from django.shortcuts import  render, redirect, get_object_or_404
from .forms import NewUserForm, UserPostForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm

# Fichier qui définit la logique en backend des différentes pages de notre site

# La page d'accueil de notre site
def accueil(request):
  template = loader.get_template('main.html')
  return HttpResponse(template.render())

# Un autre moyen d'accéder à la page d'accueil
def main(request):
  template = loader.get_template('main.html')
  return HttpResponse(template.render())

# La page pour créer un compte
def register_request(request):
	form = NewUserForm(request.POST) # On utilise le formulaire de création de publication
	if request.method == "POST":
		if form.is_valid():
			user = form.save()
			login(request, user)
			messages.success(request, "Registration successful." )
			return redirect('/accueil/')
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = NewUserForm()
	return render (request=request, template_name="register.html", context={"register_form":form}) # On affiche la template HTML de la page

# La page pour se connecter
def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None: # Si l'utilisateur est trouvé dans la base de donnée
				login(request, user)
				messages.info(request, f"You are now logged in as {username}.")
				return redirect('/accueil/') # On redirige à l'accueil
			else:
				messages.error(request,"Invalid username or password.")
		else:
			messages.error(request,"Invalid username or password.")
	form = AuthenticationForm()
	return render(request=request, template_name="login.html", context={"login_form":form}) # On affiche la template HTML de la page

# La page 'à propos de nous'
def aboutUs(request):
	template = loader.get_template('a_propos_de_nous.html')
	return HttpResponse(template.render()) # On affiche la template HTML de la page

# La page 'nous joindre'
def nousJoindre(resquest):
	template = loader.get_template('nous_joindre.html')
	return HttpResponse(template.render())

# La méthode qui permet de se déconnecter et redirige à l'accueil
def logout_request(request):
	logout(request)
	messages.info(request, "Vous vous êtes déconnecté avec succès") 
	return redirect('/accueil/')

# La page 'conditions d'utilisation'
def conditionsUtilisations(request):
	template = loader.get_template('conditions_utilisations.html')
	return HttpResponse(template.render()) # On affiche la template HTML de la page

# La page 'à lire'
def aLire(request):
	template = loader.get_template('a_lire.html')
	return HttpResponse(template.render()) # On affiche la template HTML de la page

# La liste de profils
def profile_list(request):
    profiles = Profile.objects.exclude(user=request.user)
    return render(request, "profile_list.html", {"profiles": profiles}) # On affiche la template HTML de la page

# La page qui affiche le profil d'un utilisateur
def profile(request, pk):
    profile = Profile.objects.get(pk=pk)
    profile_string = profile.user.username
    username = request.user.username
    roomname = username + profile_string
    return render(request, "profile.html", {"profile": profile, 'username': username, 'roomname': roomname, 'profile_string': profile_string}) # On affiche la template HTML de la page

# La page pour créer une publication
def dashboard(request):
    form = UserPostForm(request.POST or None)
    if request.method == "POST":
        form = UserPostForm(request.POST, request.FILES)
        if form.is_valid():
            UserPost = form.save(commit=False)
            UserPost.user = request.user
            UserPost.save()
            img_object = form.instance
            return render(request, "dashboard.html", {"form": form, 'img_obj': img_object}) # On affiche la template HTML de la page
        else:
          form = UserPostForm()

    return render(request, "dashboard.html", {"form": form}) # On affiche la template HTML de la page

# La page pour rechercher des publications
def rechercher(request):
	if request.method == "POST":
		searched = request.POST['searched']
		posts = UserPost.objects.filter(title__contains=searched)

		return render(request, 'recherche.html', {'searched':searched, 'posts':posts})
	else:
		return render(request, 'recherche.html', {}) # On affiche la template HTML de la page

# La salle de messagerie	
def room(request, room):
	username = request.GET.get('username')
	room_details = Room.objects.get(name=room)
	return render(request, 'room.html', {'username': username, 'room': room, 'room_details': room_details}) # On affiche la template HTML de la page

# Méthode qui permet de créer la salle de messagerie où d'y accéder avant de l'afficher
def checkview(request):
	room = request.POST['room_name']
	username = request.POST['username']
	profile = request.POST['profile']
	check = Room.objects.filter(name=room).exists() 
	check2 = (Room.objects.filter(name=profile+username))
	if check: # On vérifie s'il existe déjà une salle entre les deux utilisateurs
		return redirect('/rooms/'+room+'/?username='+username)
	elif check2: # On vérifie s'il existe déjà une salle entre les deux utilisateurs
		return redirect('/rooms/'+ profile + username+'/?username='+username)
	else: # S'il n'a pas déjà de salle, on en crée une
		new_room = Room.objects.create(name=room)
		new_room.save()
		return redirect('/rooms/'+room+'/?username='+username)

# Méthode qui permet d'envoyer un message	
def send(request):
	message = request.POST['message']
	username = request.POST['username']
	room_id = request.POST['room_id']

	new_message = Message.objects.create(value=message, user=username, room=room_id)
	new_message.save()
	return HttpResponse('Message envoyé avec succès')

# Méthode qui permet d'accéder à tous les messages d'une salle
def getMessages(request, room):
	room_details = Room.objects.get(name=room)

	messages = Message.objects.filter(room=room_details.id)
	return JsonResponse({"messages":list(messages.values())})


Kulimo/accueil/templates/a_lire.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>À propos de nous</title>
  </head>
    <style> 
    h1{text-align: center;}
    </style> 
  </head>
  {% include 'navbar.html' %}
  <body>
    {% block content %}
    
     <header>
       <h1 style="padding-top: 50px;">À lire</h1>
     </header>

     <div class="row">
        <div class="col-sm-3" style="background-color:rgb(255, 255, 255);">
          <p> </p>
        </div>
        <div class="col-sm-6" style="background-color:rgb(255, 255, 255);">
    
            

                
               <main>
                <p> Les activités suivants sont interdites sur Kulimo :</p>
                <ol>
                <li>Afficher des publicités pour des articles qui ne sont pas pertinents pour l'école n'est pas approprié.</li>
                <br>
                <li>Il est inapproprié de publier des annonces qui comportent des propos diffamatoires ou haineux.</li>
                <br>
                <li>Il est interdit de publier des annonces contenant une liste de mots-clés qui ne sont pas directement liés aux articles à vendre, ou dans une langue autre que le français ou l'anglais. </li>
                <br>
                <li>Les annonces ne doivent pas contenir d'informations trompeuses ou être dans une catégorie inappropriée, ni enfreindre les règlements pour les annonces d'animaux ou la politique d'égalité en matière de logement.</li>
                <li>Enfin, il est interdit de publier des annonces destinées à tirer profit d'une catastrophe naturelle, des problèmes de santé ou de sécurité publique, ou d'un événement tragique.</li>
                </ol>
             </main>




        </div>
        <div class="col-sm-3" style="background-color:rgb(255, 255, 255);">
            <p> </p>
          </div>
      </div>
    
    {% include "master.html" %}
    {% endblock %} 
  </body>
</html>

Kulimo/accueil/templates/a_propos_de_nous.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>À propos de nous</title>
  </head>
    <style> 
    h1{text-align: center;}
    </style> 
  </head>

 
  {% include 'navbar.html' %}
  <body>
  
   {% block content %}
 
    <header>
      <h1 style="padding-top: 50px;">À propos de nous</h1>
    </header>
    
    <div class="row">
        <div class="col-sm-3" style="background-color:rgb(255, 255, 255);">
          <p> </p>
        </div>
        <div class="col-sm-6" style="background-color:rgb(255, 255, 255);">
    
            

                
                            <main>
                                <section>
                                <h2>Notre histoire</h2>
                                <p>Nous sommes 3 étudiants au Collège Bois-de-Boulogne passionés par l'informatique qui essaient de faciliter la vente des livres usagés. Avec les compétences apprises dans le programme de SIM, ce premier projet serait le fruit de nos études.</p>
                                </section>
                                <section>
                                <h2>Notre équipe</h2>
                                <p>Voici notre équipe</p>
                                <ul>
                                    <li>Benjamin Morin - CEO</li>
                                    <img style = "margin: 25px; width:25%; height: 25%;" src = "{% static './img/Benjamin.jpg' %}" class = "img-fluid">  
                                    <li>Karan Kumar - Soutien technique</li>
                                    <img style = "margin: 25px; width:25%; height: 25%;" src = "{% static './img/karan2.jpg' %}" class = "img-fluid">
                                    <li>Anthony Lim - Directeur en chef du cabinet culinaire</li>
                                    <img style = "margin: 25px; width:25%; height: 25%;" src = "{% static './img/AnthonyLim.jpg' %}" class = "img-fluid">
                                </ul>
                                </section>
                                <section>
                                <h2>Notre mission :</h2>
                                <p>Notre mission est de fournir aux étudiants un outil qui permet de faciliter leurs ventes de livres usagés !</p>
                                </section>
                            </main>




        </div>
        <div class="col-sm-3" style="background-color:rgb(255, 255, 255);">
            <p> </p>
          </div>
      </div>
    






    {% include "master.html" %}
    {% endblock %} 
  </body>
</html>

Kulimo/accueil/templates/conditions_utilisations.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>À propos de nous</title>
  </head>
    <style> 
    h1{text-align: center;}
    </style> 
  </head>

  <body>
    {% include 'navbar.html' %}
    {% block content %}
    
     <header>
       <h1 style="padding-top: 50px;">Conditions d'utilisations</h1>
     </header>

     <div class="row">
        <div class="col-sm-3" style="background-color:rgb(255, 255, 255);">
          <p> </p>
        </div>
        <div class="col-sm-6" style="background-color:rgb(255, 255, 255);">
    
            

                
                            <main>
                             <p>
                                Bienvenue sur Kulimo, un site de petites annonces en ligne qui permet aux utilisateurs de publier des annonces pour vendre ou acheter des biens et services. Les présentes conditions d'utilisation régissent l'utilisation de Kulimo par les utilisateurs. En utilisant Kulimo, vous acceptez les présentes conditions d'utilisation et vous engagez à les respecter. Si vous n'acceptez pas les présentes conditions d'utilisation, veuillez ne pas utiliser Kulimo.
                                <br>
                                <br>
                                <u><strong>Inscription et compte utilisateur</strong></u>
                                <br>
                                Pour utiliser Kulimo, vous devez vous inscrire et créer un compte utilisateur. Vous êtes responsable de la confidentialité de votre compte utilisateur et de votre mot de passe. Vous acceptez de ne pas partager votre compte utilisateur ou votre mot de passe avec des tiers.
                                <br>
                                <br>
                                <u><strong>Contenu publié</strong></u>
                                <br>
                                Vous êtes responsable de tout contenu que vous publiez sur Kulimo, y compris les annonces, les photos, les descriptions et les commentaires. Vous acceptez de ne publier que du contenu licite et véridique. Vous acceptez également de ne pas publier de contenu qui est diffamatoire, offensant, obscène, discriminatoire ou qui enfreint les droits de propriété intellectuelle d'autrui.
                                <br>
                                <br>
                                <u><strong>Propriété intellectuelle</strong></u>
                                <br>
                                Kulimo détient tous les droits de propriété intellectuelle relatifs au site web, y compris les marques de commerce, les droits d'auteur et les brevets. Vous acceptez de ne pas copier, reproduire, modifier, distribuer ou utiliser de quelque manière que ce soit le contenu de Kulimo sans l'autorisation écrite préalable de Kulimo.
                                <br>
                                <br>
                                <u><strong>Limitation de responsabilité</strong></u>
                                <br>
                                Kulimo ne peut être tenu responsable de tout dommage, perte ou préjudice résultant de l'utilisation de Kulimo ou de tout contenu publié sur Kulimo. Kulimo ne garantit pas l'exactitude, la fiabilité ou la qualité du contenu publié sur Kulimo. Vous utilisez Kulimo à vos propres risques.
                                <br>
                                <br>
                                <u><strong>Résiliation</strong></u>
                                <br>
                                Kulimo se réserve le droit de résilier votre compte utilisateur et de supprimer tout contenu que vous avez publié sur Kulimo si vous enfreignez les présentes conditions d'utilisation.
                                <br>
                                <br>
                                <u><strong>Modification des conditions d'utilisation</strong></u>
                                <br>
                                Kulimo se réserve le droit de modifier les présentes conditions d'utilisation à tout moment. Les modifications prendront effet dès leur publication sur Kulimo.
                                <br>
                                <br>
                                En utilisant Kulimo, vous acceptez les présentes conditions d'utilisation et vous acceptez de respecter toutes les lois applicables.
                                </p>
                            </main>




        </div>
        <div class="col-sm-3" style="background-color:rgb(255, 255, 255);">
            <p> </p>
          </div>
      </div>
    






    {% include "master.html" %}
    {% endblock %} 
  </body>
</html>

Kulimo/accueil/templates/footer.html
{% load static %}
<head> 
    <link rel="stylesheet" href="{% static './css/style.css' %}"> 
</head>

<footer class="footer">        
    <div class = "container">
      <div class = "row">
        <div class = "footer-col">
          <h4>Kulimo</h4>
         <u1>
          <li><a href="{% url 'accueil:aboutUs' %}">A propos de nous</a></li>  
          <li><a href="{% url 'accueil:nousJoindre' %}">Nous joindre</a></li>  
         </u1>
        </div>
        <div class = "footer-col">
           <h4>Renseignements</h4>
           <u1>
            <li><a href="{% url 'accueil:conditionsUtilisations' %}">Conditions d'utilisations</a></li>  
            <li><a href="{% url 'accueil:a_lire' %}">A lire</a></li>
           </u1>
           
        </div>
      </div> 
    </div>
   <p>&copy; 2023 Kulimo. Tous les droits réservés.</p>      
  </footer>

Kulimo/accueil/templates/header.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Kulimo Bdeb</title>
  
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <title>Title</title>
  </head>
 <body>
  {% include 'messages.html' %}
    {% block content %}
    <footer class="footer">        
      <div class = "container">
        <div class = "row">
          <div class = "footer-col">
            <h4>Kulimo</h4>
           <u1>
            <li><a href="{% url 'accueil:aboutUs' %}">A propos de nous</a></li>  
            <li><a href="{% url 'accueil:nousJoindre' %}">Nous joindre</a></li>   
           </u1>
          </div>
          <div class = "footer-col">
             <h4>Renseignements</h4>
             <u1>
              <li><a href="{% url 'accueil:conditionsUtilisations' %}">Conditions d'utilisations</a></li>
             </u1>
          </div>
        </div> 
      </div>      
    </footer>
    {% include "footer.html" %}
    {% endblock %} 
      
  </body>
</html>

Kulimo/accueil/templates/list_announce.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>À propos de nous</title>
  </head>
    <style> 
    h1{text-align: center;}
    </style> 
  </head>

 
  {% include 'navbar.html' %}
  <body>
  
   {% block content %}











   {% include "master.html" %}
   {% endblock %} 
 </body>
</html>

Kulimo/accueil/templates/login.html
{% extends "header.html" %}

{% load static %}
{% load crispy_forms_tags %}
{% block content %}    

<!--Login--> 
<div class="container py-5">
  <h1>Se connecter</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-primary" type="submit">Se connecter</button>
  </form>
  <p class="text-center">Vous n'avez pas de compte? <a href="/register">Créez en un</a>.</p>
</div>

{% endblock %}

Kulimo/accueil/templates/messages.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

Kulimo/accueil/templates/navbar.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="stylesheet" href="{% static './css/style.css' %}"> 
  <style>
  </style>
</head>
<body>

    <nav class="navbar navbar-default navbar-fixed-top">
        
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/accueil/"><img style="width: 90%; height: 90%;" src = "{% static './img/logo.png' %}" class = "img-fluid"></a>
          </div>
          <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav navbar-right" style="padding-right: 25px;">
              <li><a href="{% url 'accueil:aboutUs' %}">A propos de nous</a></li>  
              <li><a href="{% url 'accueil:nousJoindre' %}">Nous joindre</a></li>  
              <li><a href="{% url 'accueil:conditionsUtilisations' %}">Conditions d'utilisations</a></li>
              <li><a href="{% url 'accueil:a_lire' %}">A lire</a></li>

              {% block content %} 
                {% if user.is_authenticated %}

                <li class="nav-item">
                  <a class="nav-link" href="/logout">Se deconnecter</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">Bienvenue, {{user.username}}</a>
                </li>
          
                {% else %}
          
                <li class="nav-item">
                  <a class="nav-link" href="/login">Se connecter</a>
                </li>
          
                {% endif %}
              {% endblock content %}
            </ul>
          </div>
        
      </nav>    

Kulimo/accueil/templates/profile_list.html
{% load static %}

<!DOCTYPE html>
<head>
    <title>Kulimo BdeB</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static './css/style.css' %}"> 
  </head>

{% block content %}
<div style="background-color: #1756a3;"> 
    <img style = "margin: 25px; align-items: center; padding-left: 22%; padding-right: 12%;" src = "{% static './img/logo.png' %}" class = "img-fluid">  
 
</div>

<br></br>
<strong style="font-size: 200%; padding-left: 17.5%;">Voici la liste des utilisateurs, cliquez sur leurs noms pour voir les articles qu'ils vendent :</strong>
<br></br>
<div class="row test">
<div class = "col-md-4"></div>  
<div class="col-md-3">
   
{% for profile in profiles %}

  
    <style>
        li{
            font-size: 200%;
            text-align: left; 
            padding-bottom: 10px;
            padding-left: 45%;
        
        }
    </style>
    
    <li><a href="{% url 'accueil:profile' profile.id %}">{{ profile.user.username }}</a></li>
    
{% endfor %}
</div>  
<div class =" col-md-5" ></div>
</div>
{% endblock content %}
{% include "master.html" %}

Kulimo/accueil/templates/recherche.html
{% load static %}
{% include 'navbar.html' %}
<head>
    <title>Kulimo BdeB</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  </head>
{% block content %}

<form class="d-flex" method=POST action="{% url 'rechercher' %}"  style="padding-top: 5%;">
    {% csrf_token %}
    <input class="form-control me-2" type="search" placeholder="Rechercher" aria-label="Search" name="searched">
    <button onclick="location.href = '/rechercher';" class="btn btn-outline-secondary" type="submit">Rechercher</button>
  </form>

{% if searched %}
    <h1>Vous avez recherché: {{ searched }} . Voici les publications les plus pertinentes: </h1>
    <br>
    {% for userpost in posts %}
    <div class="box">
        <div class = "col-md-5"></div>
        <div class = "col-md-6"></div>
        <div class = "col-md-1"></div>   
        <strong style="font-size: 250% ; padding: 2%;">{{ userpost.title }}</strong>
         
        <div style="font-size: 150%; padding-left: 3%;">{{ userpost.content }}</div> 
        
        <img style="width: 50%; height: auto; padding: 2%; overflow: hidden; " src="{{ userpost.image.url }}">
        <br>
       
    
        
        
        <span class="is-small has-text-grey-light">
            (Publié par <a href="{% url 'accueil:profile' userpost.user.profile.id %}">{{ userpost.user }}</a> le {{ userpost.date_published }})
        </span>
        
     <hr style="height: 3px; background-color: lightslategray;">   
    </div>

    {% endfor %}

    {% else %}
        <h1>Vous n'avez rien recherché...</h1>
{% endif %}
{% endblock %}
{% include "master.html" %}

Kulimo/accueil/templates/register.html
{% extends "header.html" %}

{% block content %} 

{% load crispy_forms_tags %}         

<!--Register--> 
<div class="container py-5">
	<h1>Créer un compte</h1>
	<form method="POST">
		{% csrf_token %}
		{{ register_form|crispy }}                    
		<button class="btn btn-primary" type="submit">Créer le compte</button>
	</form>
	<p class="text-center">Si vous avez déjà un compte, <a href="/login">connectez-vous</a> </p>
</div>

{% endblock %}